### ISSUE TITLE
Maintainer wanted for Feliz.MaterialUI

### ISSUE THREAD

**Issue by cmeeren** [Shmew/Feliz.MaterialUI#72]
I am looking for someone to take over this repo. The reasons for this are:

* Long-running capacity constraints on my part
* I don't actively use it (or Fable at all)
* The library seems to be used by quite a few people
* MUI v5 is coming (no idea when)

Maintaining this library hasn't been much work as Material-UI itself hasn't seen many changes for a while now, but I expect that to pick up when v5 is released.

The work I have done so far has mostly consisted of updating the bindings for new versions of MUI. The steps for this are described in the readme. The only non-mechanical work is in step 2:

> Check all changes to Feliz.MaterialUI and adjust the generator’s API parser as needed.

In practice, this mostly entails editing/adding new cases in [ApiParser.fs](https://github.com/cmeeren/Feliz.MaterialUI/blob/master/src/Feliz.Generator.MaterialUI/ApiParser.fs), specifically in the [`regularOverloads` section](https://github.com/cmeeren/Feliz.MaterialUI/blob/f6790e46b86cf328153a9435d1c49521ba53797c/src/Feliz.Generator.MaterialUI/ApiParser.fs#L82). Figuring out the actual types to use in the arguments for each prop etc. sometimes require digging into MUI source code, but mostly it's documented clearly and in a way that the parser understands.

Anyone who takes over is of course free to steer Feliz.MaterialUI in whatever direction they desire, refactor with wild abandon, etc.

I will be available for questions etc. in a transition period.

**Comment by Shmew** [comment]
Hey @cmeeren,

I can take over the repo for you. 

I built Feliz.Plotly from a fork of your generator so I'm quite familiar with it and I already have a couple libraries for other material-ui stuff. With these in mind I likely won't need to bug you much if at all.

**Comment by cmeeren** [comment]
That is wonderful, @Shmew! Thank you so much. I'll make the arrangements.

**Comment by cmeeren** [comment]
You have to delete your fork of Feliz.MaterialUI before I can transfer ownership.

**Comment by cmeeren** [comment]
By the way, are you interested in https://github.com/cmeeren/Fable.MaterialUI.Icons and https://github.com/cmeeren/Fable.MaterialUI.MaterialDesignIcons, too? They are practically maintenance free. I have to let go of them, too.

**Comment by Shmew** [comment]
Okay I deleted my fork.

> By the way, are you interested in Fable.MaterialUI.Icons and Fable.MaterialUI.MaterialDesignIcons, too? They are practically maintenance free (see the notes at the bottom of the readmes). I have to let go of them, too.

Yeah sure I can do that.

**Comment by cmeeren** [comment]
Great! I have started the transfer. You likely need to approve. This goes for the NuGet packages, too.
